### ISSUE TITLE
Feedback on Version 5 of the Paper

### ISSUE THREAD

**Issue by cyjwong** [jgerity/uspas2016_project3#9]
In the paragraph before equation (6), there is a sentence which says that "Therefore, the number of turns N_turns is limited by the selected 10cm horizontal apertures x_max of the bending magnets"
I believe 10cm is the aperture of the quads, and it is the quads, not the dipoles, that limit the number of turns.

I wonder if equation 6 is erroneous. From 
![equation](https://cloud.githubusercontent.com/assets/13799496/18499611/799adb7c-7a0e-11e6-83e2-dcfc3ea75502.png)
where delta_E is the energy loss per turn, and N*delta_E denotes the max. allowed energy loss. This divided by the total E should equal the max. allowed dispersive shift divided by the dispersion function.
Hence the modified equation would be of the form:
![equation](https://cloud.githubusercontent.com/assets/13799496/18499601/683202d4-7a0e-11e6-8542-23301ebe3817.png)

In Table 3, I believe the bending radius and dispersion function of the 1 GeV s.c. case should be 0.33m rather than 0.83m

In the last sentence of the first paragraph in Discussion, it mentions a beam size of sigma_r = 5 micron. I am not sure I understand this correctly, because, according to Table 3, the beam size is at least 500 micron when the electron beam is circling the ring.

**Comment by MarleneTurner** [comment]
Hi Jonathan, Where did you get this formula 6 from?
Because I have this version [cid:image001.png@01D20EAF.B8610F40]  from Brandon.

**Comment by ghost** [comment]
Hi Jonathan,

Where did you get this equation from? because in the last version I sent out formula 6 is different. (I got it from Brandon)
[na_pac_uspas_v5.pdf](https://github.com/jgerity/uspas2016_project3/files/472578/na_pac_uspas_v5.pdf)

Thanks for the bending radius and dispersion, that was indeed a typo.

**Comment by cyjwong** [comment]
Hi Marlene, I believe formula 6 in the latest version has an error, and the equations I showed are what I thought should be the correct form of formula 6. 

The existing formula fails a dimensional analysis. The left hand side, N_turns, is dimensionless, whereas the right hand side has dimension (eV)^-1. 

I am sorry for the confusing notation in my initial post. Capital-delta_E was meant to be the energy loss per turn.
![equation](https://cloud.githubusercontent.com/assets/13799496/18534506/d99f30d0-7ab9-11e6-924f-9c5283262210.png)

Perhaps this would be clearer:

x_max - 2*delta-x is the maximum allowed dispersive shift. It should equal the dispersion function times the maximum allowed fractional energy loss.
![equation](https://cloud.githubusercontent.com/assets/13799496/18534307/ba08951a-7ab7-11e6-83ff-2677b1e58524.png)
The maximum allowed energy loss equals the energy loss per turn times N_turn.
![equation](https://cloud.githubusercontent.com/assets/13799496/18534512/e3c36c84-7ab9-11e6-8eb7-63841a46e41c.png)

Rearranging the terms lead to:
![equation](https://cloud.githubusercontent.com/assets/13799496/18534536/225d04be-7aba-11e6-972c-36ce4850b711.png)

**Comment by ghost** [comment]
you're right, thanks a lot!
